= Vision

Smesh's vision is to provide a generalized way to establish and maintain a cluster with multiple Java-based (Micro-)services
as well as enabling IPC across the cluster members.

Regardless of the internal complexity of Smesh, it should be easy to setup Smesh in one's application.
i.e. no code are required for basic use cases.

== Business aspects

Smesh is designed to be used for small projects, only maintaining a few services, as well as full-fledged enterprise systems,
containing a wide variety of different services and huge clusters.

== Technical aspects

Smesh's modules utilize well-known technologies and enriches them with a generalized way to share available services and their APIs,
either via a centralized service registry or maintaining a client-side registry.
Additionally, Smesh establishes and maintains the respective service cluster.

It is not a goal to create a new IPC-protocol (e.g. https://github.com/google/protobuf[Protobufs]),
but instead rely on established technologies, such as http://www.grpc.io/[gRPC] and https://hazelcast.org/[HazelCast].

== Structural aspects

Technologies backing Smesh's functionality should be interchangeable by switching one Smesh module with another. e.g. smesh-hazelcast with smesh-grpc.
As these technologies are mostly incompatible with each other, it is required that Smesh provides custom interfaces to provide the necessary interchangeability.

== Operational aspects

Smesh's features should be monitorable and configurable at runtime, although the later is no strict requirement,
but rather a recommendation.
In addition, Smesh should provide a way to manage all connected cluster-members via a dedicated control-service offering a respective interface.

== Disclaimer

Substantial changes to this document must be reviewed with one of the project leads.